version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # 對映 Vite 開發伺服器的端口
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true